version: "3.8"

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    environment:
      SERVER_URL: http://server:3000
      DEBUG: cronyx:*
    command: sleep infinity
